<?php

/**
 * @file
 * Functions to support theming in the Bartik theme.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Template\Attribute;

/**
 * Implements template_preprocess_paragraph().
 */
function as220_preprocess_paragraph(&$variables) {
  $variables['flowpos'] = "flow_" . strtolower($variables['elements']['field_flow_position'][0]['#markup']);
  unset($variables['elements']['field_flow_position']);
}

